[package]
name = "zero_deep_rust"
version = "0.1.0"
authors = ["ariririri"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.12.1"
image = "0.22.1"
num-complex = "0.2.0"